const GameConst = {
  BATTLE: 'BATTLE',
  POWER: 'POWER',
  GAME: 'GAME',
  //
  RED: 'RED',
  BLUE: 'BLUE',
  GREEN: 'GREEN',
  BLACK: 'BLACK',
  WHITE: 'WHITE',
  BROWN: 'BROWN',
  //
  CARDS_IN_DECK: 'CARDS_IN_DECK',
  CARDS_IN_HAND: 'CARDS_IN_HAND',
  CARDS_IN_TRASH: 'CARDS_IN_TRASH',








  ATTACK_POINTS: 'ATTACK_POINTS',
  HEALTH_POINTS: 'HEALTH_POINTS',
  RED_POINTS: 'RED_POINTS',
  BLUE_POINTS: 'BLUE_POINTS',
  GREEN_POINTS: 'GREEN_POINTS',
  BLACK_POINTS: 'BLACK_POINTS',
  WHITE_POINTS: 'WHITE_POINTS',
  NUM_CARDS_IN_DECK: 'NUM_CARDS_IN_DECK',
  NUM_CARDS_IN_HAND: 'NUM_CARDS_IN_HAND',
  NUM_CARDS_IN_TRASH: 'NUM_CARDS_IN_TRASH',
  LINE_TEXT: 'LINE_TEXT',
  TEXT_START: 'TEXT_START',
  CHANGE_COLOR: 'CHANGE_COLOR',
  START: 'START',
  LEFT: 'LEFT',
  CENTER: 'CENTER',
  RIGHT: 'RIGHT',
  END: 'END',
  TOP: 'TOP',
  ABOVE_MIDDLE: 'ABOVE_MIDDLE',
  MIDDLE: 'MIDDLE',
  BELOW_MIDDLE: 'BELOW_MIDDLE',
  BOTTOM: 'BOTTOM',
  RED_COLOR: 'RED_COLOR',
  BLUE_COLOR: 'BLUE_COLOR',
  FPS: 60,
  START_PHASE: 'START_PHASE',
  END_PHASE: 'END_PHASE',
  START_SELECT_FOLDER: 'START_SELECT_FOLDER',
  END_SELECT_FOLDER: 'END_SELECT_FOLDER',
  START_CARD_DRAW_GAME: 'START_CARD_DRAW_GAME',
  END_CARD_DRAW_GAME: 'END_CARD_DRAW_GAME',
  START_DRAW_CARDS: 'START_DRAW_CARDS',
  END_DRAW_CARDS: 'END_DRAW_CARDS',
  BEGIN_LOAD_PHASE: 'BEGIN_LOAD_PHASE',
  PLAYER_LOAD_PHASE: 'PLAYER_LOAD_PHASE',
  CHALLENGE_LOAD_PHASE: 'CHALLENGE_LOAD_PHASE',
  END_LOAD_PHASE: 'END_LOAD_PHASE',
  WAITING_PHASE: 'WAITING_PHASE',
  ACTIVE_POWER_CARD: 'ACTIVE_POWER_CARD',
};

const CardTypes = {
  BATTLE: 1,
  POWER: 2,
  GAME: 3
};

const ColorTypes = {
  RED: 1,
  GREEN: 2,
  BLUE: 3,
  WHITE: 4,
  BLACK: 5,
  BROWN: 6,
};

const IconSetConst = {
  REDBOX: 309,
  BLUEBOX: 312,
  GREENBOX: 311,
  WHITEBOX: 307,
  BLACKBOX: 308,
  BROWNBOX: 310,
  DECK: 296,
  HAND: 142,
  TRASH: 235,
  SAPPHIRE: 161,
  RUBY: 162,
  BLUESAPPHIRE: 165
};

const GameColors = {
  DEFAULT: 'DEFAULT',
  BLUE: 'BLUE',
  RED: 'RED',
  GREEN: 'GREEN',
  BLACK: 'BLACK',
  WHITE: 'WHITE',
  BROWN: 'BROWN',
  FADEDRED: 'FADEDRED',
  FADEDGREEN: 'FADEDGREEN',
  FADEDBLUE: 'FADEDBLUE',
  FADEDWHITE: 'FADEDWHITE',
  FADEDBLACK: 'FADEDBLACK',
  FADEDBROWN: 'FADEDBROWN',
  //
  LIGHTBLUE: 'LIGHTBLUE',
  LIGHTRED: 'LIGHTRED',
  LIGHTGREEN: 'LIGHTGREEN',
  LIGHTBLUE2: 'LIGHTBLUE2',
  LIGHTPURPLE: 'LIGHTPURPLE',
  LIGHTYELLOW: 'LIGHTYELLOW',
  LIGHTGRAY: 'LIGHTGRAY',
  GRAY: 'GRAY',
  BLUE2: 'BLUE2',
  PURPLE: 'PURPLE',
  YELLOW: 'YELLOW',
  BLUE3: 'BLUE3',
  YELLOW2: 'YELLOW2',
  RED2: 'RED2',
  BLACK2: 'BLACK2', 
  ORANGE: 'ORANGE',
  YELLOW3: 'YELLOW3',
  GREEN2: 'GREEN2',
  GREEN3: 'GREEN3',
  LIGHTGREEN2: 'LIGHTGREEN2',
  BLUE4: 'BLUE4',
  PINK: 'PINK',
  GREEN4: 'GREEN4',
  LIGHTGREEN3: 'LIGHTGREEN3',
  VIOLET: 'VIOLET',
  LIGHTVIOLET: 'LIGHTVIOLET',
};
